### PR TITLE
- usage of smarty names message_erreur/themeForm to have compatibilit…

### PR DESCRIPTION
**Pull request by ggoffy**
…y with existing themes

- adopted modfile.tpl (caused error if used together with blocks)
- skip captcha for xoopsUsers (members are skipped in class/download.php getForm)

### CODE REVIEW

**Comment by GregMage** [comment]
Hi

I do not agree with this change:

> skip captcha for xoopsUsers (members are skipped in class/download.php getForm)

The choice is here:
[https://github.com/XOOPS/XoopsCore25/blob/master/htdocs/class/captcha/config.php](url)

by default if one is a member it is not displayed. It is not the module that must choose but the configuration file.

**Comment by ggoffy** [comment]
Hi Gregory

the problem was that in class/downloads.php it was defined that captcha will be shown only to non-members. when I wanted to save on user side I got always the error, that captcha is not matching.

is there another solution possible?

**Comment by GregMage** [comment]
Hi I have no problem! It works...

**Comment by ggoffy** [comment]
Hi Gregory

then I have to test again. I had this problems and I thought:  if captcha isn't shown in the form it make no sense to verify the captcha. so I skipped the verification (not the captcha).

but i can try to find out where the problem is

**Comment by GregMage** [comment]
If you can give me an example of an error, that's fine. If captcha is not displayed it should not have an error message. This always worked before any changes.

**Comment by ggoffy** [comment]
I will test again ;-)

**Comment by ggoffy** [comment]
now it works without message. I will remove the skip ;-)

**Comment by GregMage** [comment]
Perfect

**Pull request merged**
