### PR TITLE
Feature/feedback

### PR DESCRIPTION
**Pull request by mambax7**
Conversion attempt from MastopPublish. Is this of any value?

### CODE REVIEW

**Comment by ggoffy** [comment]
Hi

it would be nice if we stay in english when we are coding, and not 
`mpu_apagaPermissoesPai`

**Comment by mambax7** [comment]
You're absolutely right! This was just a copy and paste from MastopPublish, and I'll fix it.

**Comment by ggoffy** [comment]
can you please check language constants. they are missing _AM_ and _MI_

**Comment by mambax7** [comment]
Goffy, did you actually test the Feedback tab? This might not be ready yet, I was looking for feedback from both of you if we should include it. 
We might need to reverse it, unless you tested and you like it.

**Comment by ggoffy** [comment]
no, i didnt test it till now. maybe i have time this weekend

**Comment by ggoffy** [comment]
If I understand right you want to implement a simple form to give the user the possibility to contact module developer.
Idea is nice.
But i would make a class file in folder 'class' for the form and not in include
to make it easy for copy/paste to over modules i would suggest to make own language files (e.g. language/english/feedback.php

what is your opinion?

**Comment by mambax7** [comment]
There code was taken from the MastopPublish, and I've included it just to show you the idea, so I didn't make any changes to it. 
If we like the idea, then, of course, we would rewrite it into a generic class in /class and a form in /class/forms, that could be easily copied to other modules, and then eventually included in XMF

**Comment by ggoffy** [comment]
Hi Michael

Have you seen  that I implemented a version of feedback to wgGallery. is this what you expect? if yes, I will implement it to tdmdownload

**Comment by mambax7** [comment]
No, I didn't. I'll check it out.

**Comment by mambax7** [comment]
Yes, the Feedback looks nice there.

**Pull request merged**
