### PR TITLE
Fix:Warning: count() with php 7.2

### PR DESCRIPTION
**Pull request by GregMage**

### CODE REVIEW

**Comment by mambax7** [comment]
Why not checking first if it is an array? 
```php
if (is_array($viewDownloads) && 0 === count($viewDownloads)) 
```

**Comment by GregMage** [comment]
If $viewDownloads is not an array you have an error with count($viewDownloads) in php 7.2

**Comment by mambax7** [comment]
But shouldn't the first check if it is array? 
See this comment in the discussion on using empty():

> Strings also aren't empty, among other things

https://stackoverflow.com/questions/42899605/how-to-check-if-something-is-countable?noredirect=1&lq=1

**Comment by mambax7** [comment]
This solution got more votes:
```php
if (is_array($foo) || $foo instanceof Countable) {
    return count($foo);
}
```

**Comment by mambax7** [comment]
The other option would be:
```php
if ($viewDownloads && is_array($viewDownloads)) 
```

**Comment by mambax7** [comment]
I was probably too fast :) 
I see that you're testing if an array is empty, so this would work, but we have to make sure that indeed the variable is an array, right? 
This is a good overview of the different results for empty():
https://www.virendrachandak.com/techtalk/php-isset-vs-empty-vs-is_null/

**Pull request merged**
