### PR TITLE
Feature/different blockstyles

### PR DESCRIPTION
**Pull request by ggoffy**

### CODE REVIEW

**Comment by mambax7** [comment]
I am not sure if this is related to these changes, or if these are pre-existing problems, and I didn't have time to look deeper into it, but I'm getting  following notices:
```
Notice: Undefined offset: 0 in file /modules/tdmdownloads/blocks/tdmdownloads_top.php line 70 
Notice: Undefined variable: select_sup in file /modules/tdmdownloads/blocks/tdmdownloads_search.php line 130
```
In queries, I have following errors (I'm using MySQL 5.7.22):
```sql

0.000129 - SELECT * FROM `tdmdownloads_downloads` WHERE (`cid` IN (2,1,3) AND `cid` IN () AND `status` != '0') ORDER BY date DESC LIMIT 0, 10Error number: 1064Error message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND `status` != '0') ORDER BY date DESC LIMIT 0, 10' at line 1
--
0.000568 - SELECT * FROM group_permission WHERE (`gperm_name` = 'tdmdownloads_view' AND `gperm_modid` = '51' AND (`gperm_groupid` = '1' OR `gperm_groupid` = '2'))
0.000132 - SELECT * FROM `tdmdownloads_downloads` WHERE (`cid` IN (2,1,3) AND `cid` IN () AND `status` != '0') ORDER BY hits DESC LIMIT 0, 10Error number: 1064Error message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND `status` != '0') ORDER BY hits DESC LIMIT 0, 10' at line 1
0.000618 - SELECT * FROM group_permission WHERE (`gperm_name` = 'tdmdownloads_view' AND `gperm_modid` = '51' AND (`gperm_groupid` = '1' OR `gperm_groupid` = '2'))
0.000216 - SELECT * FROM `tdmdownloads_downloads` WHERE (`cid` IN (2,1,3) AND `cid` IN () AND `status` != '0') ORDER BY rating DESC LIMIT 0, 10Error number: 1064Error message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND `status` != '0') ORDER BY rating DESC LIMIT 0, 10' at line 1
0.000578 - SELECT * FROM group_permission WHERE (`gperm_name` = 'tdmdownloads_view' AND `gperm_modid` = '51' AND (`gperm_groupid` = '1' OR `gperm_groupid` = '2'))
0.000124 - SELECT * FROM `tdmdownloads_downloads` WHERE (`cid` IN (2,1,3) AND `cid` IN () AND `status` != '0') ORDER BY RAND() ASC LIMIT 0, 10Error number: 1064Error message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND `status` != '0') ORDER BY RAND() ASC LIMIT 0, 10' at line 1

```

**Comment by ggoffy** [comment]
have you updated the module? I think not ;-)

**Comment by mambax7** [comment]
Yes, I did, and I cleared the cache.
This is what I'm getting in blocks:
image

**Comment by ggoffy** [comment]
which theme are you using?

**Comment by mambax7** [comment]
xbootstrap

**Comment by ggoffy** [comment]
I think I know, give a a few minutes

**Comment by mambax7** [comment]
On the Default  theme, I'm getting this, so it looks like the cards are working here:
image

**Comment by ggoffy** [comment]
should look like http://fxgruber.at.185-101-158-246.139.hosttech.eu/modules/wglinks/index.php?link_catid=2 
:-)

**Comment by mambax7** [comment]
There are obviously issues with your CSS

**Comment by ggoffy** [comment]
read mail. pushing solution is not working :-(

**Comment by mambax7** [comment]
Of course, it works!!! If you commit to the correct branch! :) 
image

**Comment by ggoffy** [comment]
grafik

**Comment by ggoffy** [comment]
grafik

**Comment by mambax7** [comment]
If you're fixing the issue in https://github.com/XoopsModules25x/tdmdownloads/pull/47, then you should commit the fix to this branch:
https://github.com/ggoffy/tdmdownloads/tree/feature/different_blockstyles
and not to the "master"

**Comment by mambax7** [comment]
Or is https://github.com/XoopsModules25x/tdmdownloads/pull/49 not related at all to https://github.com/XoopsModules25x/tdmdownloads/pull/47 ?

**Comment by ggoffy** [comment]
as I am not understanding the system i don't know

**Comment by ggoffy** [comment]
I will go back to "old school"
stupid fork
stupid pull request

**Comment by mambax7** [comment]
No, don't do it! :) 
Invest some time now, and you'll be way more productive in the future! :) 

Just pay attention to what you're fixing and it which branch!

**Comment by ggoffy** [comment]
https://github.com/XoopsModules25x/tdmdownloads/pull/50

**Pull request closed without merging**
