### PR TITLE
fix error weight

### PR DESCRIPTION
**Pull request by GregMage**

### CODE REVIEW

**Comment by ggoffy** [comment]
I think this is impossible (cannot be both)
if ((int)$_REQUEST['cat_weight'] == 0 && $_REQUEST['cat_weight'] != '0') {

should this be: 
if ((int)$_REQUEST['cat_weight'] == 0) {

with XMF
if ( 0 == \Xmf\Request::getInt('cat_weight', 0, 'POST')  ) {

**Comment by GregMage** [comment]
I do not want the value "0" to be considered wrong. I did not find any other way ...

**Comment by mambax7** [comment]
Why not then:
if ('' === \Xmf\Request::getInt('cat_weight', '', 'REQUEST')) {

If 'cat_weight' is '0', then getInt() will return 0, right?

**Comment by GregMage** [comment]
Perhaps. We must test

**Comment by GregMage** [comment]
It does not work. Sorry

**Comment by ggoffy** [comment]
would you like to allow 0 ?

**Comment by mambax7** [comment]
Mage, what are you getting as a result of this, when you use '0', i.e. a string in 'cat_weight'?
 \Xmf\Request::getInt('cat_weight', '', 'REQUEST')

**Comment by mambax7** [comment]
BTW - this is wrong and needs to be fixed. Is this the same problem? 
image

**Comment by mambax7** [comment]
I would just delete this check
```php
        if (0 === \Xmf\Request::getInt('cat_weight', 0, 'REQUEST')) {
            $erreur         = true;
            $errorMessage = _AM_TDMDOWNLOADS_ERREUR_WEIGHT . '<br>';
        }
```

and set it to a numeric 0 as a default.

**Comment by GregMage** [comment]
> would you like to allow 0 ?

yes

**Comment by mambax7** [comment]
But this does allow a 0 for you:
```php
$obj->setVar('cat_weight', \Xmf\Request::getInt('cat_weight', 0, 'POST'));
```
I'm not sure, I understand the issue here...

**Comment by ggoffy** [comment]
for me the same. at the moment I do not understand the problem :-|

**Comment by GregMage** [comment]
When I have this:
image

I have the error message:

image

I do not want an error message when I put 0. My fix corrects the problem. I hope my explanation is clearer ...

**Comment by mambax7** [comment]
Exactly. To fix it do the following:
a) delete this check
```php
        if (0 === \Xmf\Request::getInt('cat_weight', 0, 'REQUEST')) {
            $erreur         = true;
            $errorMessage = _AM_TDMDOWNLOADS_ERREUR_WEIGHT . '<br>';
        }
```

b) and set it to a numeric 0 as a default with:
```php
$obj->setVar('cat_weight', \Xmf\Request::getInt('cat_weight', 0, 'POST'));
```
I tested, and it works perfectly

**Comment by GregMage** [comment]
Now you put a letter in the form and there is no error message ....

You have not tested 100% ;-)

**Comment by mambax7** [comment]
Think "Convention over Configuration" :) 
What is the goal of it? We want to set default to 0, right? If the user types a different number, it will be properly saved.
If the user does nothing, or he types a non-numeric value, it will be set to the default, i.e. to 0
Why would you want to add extra error message? 
You might add it in the field description: "Enter numeric value, otherwise it will be set to 0 as a default"

**Comment by GregMage** [comment]
That's how I work. But there are many ways to do it. My solution is the one that changes the module the least (no need to change language definitions)

**Comment by ggoffy** [comment]
I also think we should remove the check and take 0 as default.

But if I understand you right then you want to ensure that in the field "weight" is a numeric value. 
why not using:
`if (!is_numeric($_POST['cat_weight'])) {`

**Comment by GregMage** [comment]
I understand, you do not like my solution.

We will use the solution:

`$obj->setVar('cat_weight', \Xmf\Request::getInt('cat_weight', 0, 'POST'));`

**Pull request closed without merging**
